name: 'sample workflow'
on: workflow_dispatch
jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello
      - run: echo "Hello World"
      - name: printBye
      - run: echo "My work done Bye"
      
